version: '3.8'
services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
        - 1521:1521
        - 5500:5500
    environment:
        - ORACLE_PASSWORD=oracle
    volumes:
        - ./oracle-data:/opt/oracle/fatec
volumes:
    oracle-data: